name: Generate Proto stubs
run-name: Generating

on:
    push:
        branches:
            - main
        tags:
            - "*"

jobs:
    generate:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: ["order"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Etract Release Version
              run: echo "RELEASE_VERSION=v1.0.0" >> $GITHUB_ENV

            - name: Running Shell Script
              shell: bash
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/genScript.sh"
                  ls -alh ${GITHUB_WORKSPACE}
                  ./genScript.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com

            - name: Commit and push changes
              run: |
                  git config user.name "iAmGreatt"
                  git config user.email "greatjohncena9@gmail.com"
                  git add .
                  git commit -m "Generate protobuf code"
                  git push origin main  # Adjust branch name as necessary
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
