name: Generate Proto stubs
run-name: Generating

on:
    push:
        branches:
            - main
        tags:
            - "*"

permissions: write-all

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    generate:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service: ["order", "payments", "shipping"]
                # Optionally, you can add a `max-parallel` key to limit the number of jobs running in parallel
                # max-parallel: 1
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Release Version
              run: echo "RELEASE_VERSION=v1.0.0" >> $GITHUB_ENV

            - name: Pull Repo
              run: git pull

            - name: Running Shell Script
              shell: bash
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/genScript.sh"
                  ls -alh ${GITHUB_WORKSPACE}
                  ./genScript.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }} ${{ github.actor }} ${{ github.actor }}@users.noreply.github.com

            - name: Commit and push changes
              run: |
                  git config user.name "iAmGreatt"
                  git config user.email "greatjohncena9@gmail.com"
                  git add .
                  git commit -m "Generate protobuf code"
                  git push origin main  # Adjust branch name as necessary
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
